### ISSUE TITLE
The Chest on the SkyBlock isle is Invisible

### ISSUE THREAD

**Issue by DragonfireHD** [andresbytes/SkyBlock#200]
I create a isle but the Chest on the Isle is invisible pls fix them

**Comment by GiantQuartz** [comment]
Could you tell the exact steps you to reproduce this issue and the SkyBlock version you're using?

**Comment by MasApip** [comment]
I have same problem on version 3.0.0

**Comment by MasApip** [comment]
I mind, this bug is from minecraft not the SkyBlock

**Comment by XDslapper** [comment]
Same, idk i think its by some bad generation... :( i am so sad, i need it.

**Comment by x-lIlIlIlIl** [comment]
Easy fix  CustomChestContent:
  basic: [1]
  lost: []
  op: []
  palm: []
  shelly: []

**Comment by testloldhdid** [comment]
Its bacuse of world protect do these steps if you want to make the chest apear
1. Disable world protect
2.install world guard or world protect
3.for world guard you also need world edit the pluging is called builder tooll after you got the pluging do //want the select the corners of your lobby/build you want to protect (i recomend watching a builder tools tutorial)then do /rg define [insert build name] then disable everything that could destroy your build(i also recomend watching a tutorial for this plugin/for world protect do /wp lock (no one can build or break) or /wp protect (only people that are oped can build and break) i am not sure that thats the comand 
4. Enjoy
World protect didnt work sometimes so now i will try world guard (world protect is old)

**Comment by testloldhdid** [comment]
Btw the items in the chest should apear too

**Comment by testloldhdid** [comment]
The last step is actualy step 4 i miss spelled and put 2
