### ISSUE TITLE
[READ] How to support SkyBlock and my open-source projects

### ISSUE THREAD

**Issue by andresbytes** [andresbytes/SkyBlock#211]
A few days ago, an owner of a small server that used this plugin asked me if I could implement a feature he needed for his server. He said he had been using this plugin for years, and he really valued all the effort I (and the rest of contributors) have done to keep this project alive for more than 4 years since its first public release, however, he said he had very limited resources and therefore couldn't sponsor the project. This is why I am opening this issue, to let all of you know that there are different ways to support me and this project that I really value, these small things keep my motivation high and give me a reason to keep making free and open source projects for the Minecraft community.

Star my projects or follow me in GitHub:
https://github.com/andresbytes
<img width="519" alt="Screenshot 2020-07-07 at 13 56 31" src="https://user-images.githubusercontent.com/21067195/86777617-aae55500-c059-11ea-91f6-3d36db4276aa.png">
Every time you star one of my projects or follow me, you're showing publicly your interest for it. Today, July 7, 2020, SkyBlock has 70 stars, and that's one of the main reasons why I keep maintaining it. At least 70 people are interested in my work.

Follow me on twitter:
https://twitter.com/andresbytes
This is where I get a little more personal and talk about things that usually have nothing to do with Minecraft. I enjoy interacting with others and sharing good memes, if you post cool content I will probably follow you too!

**Comment by reyyan987** [comment]
Good
