### ISSUE TITLE
A few questions about the making island generators

### ISSUE THREAD

**Issue by Endermanbugzjfc** [andresbytes/SkyBlock#222]
# I have a question, how did you make the island generators lmao. And how long did it took?

**Comment by Endermanbugzjfc** [comment]
Bruh I spent entire week just to turn a sky island to generator codes...

**Comment by Endermanbugzjfc** [comment]
Any efficiency ways please?

**Comment by Diduhless** [comment]
I don't think it's that hard, you can check [this](https://github.com/andresbytes/SkyBlock/blob/stable/src/room17/SkyBlock/island/generator/presets/BasicIsland.php) simple generator or you could make your own parser to make [this](https://github.com/andresbytes/SkyBlock/blob/stable/src/room17/SkyBlock/island/generator/presets/ShellyGenerator.php) easier (ex. foreaching all the blocks of a chunk then saving them up on a .json)

**Comment by Endermanbugzjfc** [comment]
# K, thanks!
