### ISSUE TITLE
Wrong typed message

### ISSUE THREAD

**Issue by OguzhanUmutlu** [andresbytes/SkyBlock#228]
https://github.com/andresbytes/SkyBlock/blob/63c9a69ad21db776a361846d08c5af2ef3f3ad54/resources/messages.json#L51

"DENY_USAGE" is /is accept
it should be /is deny

You are welcome ;)

**Comment by Adam1609** [comment]
You can make a pull request to contribute to the project. No need to open an issue because it is not that important

**Comment by Diduhless** [comment]
Thank you for reporting the issue!
